### ISSUE TITLE
cannot 'make' the project

### ISSUE THREAD

**Issue by sobhonium** [VUKOZ-OEL/3d-forest#4] opened 2023-08-03 10:36 UTC
I try to make this project in build folder but I get this:

~/Documents/forest/3d-forest/src/core/Time.cpp: In static member function ‘static std::string Time::strftime(const char*)’:
~/Documents/forest/3d-forest/src/core/Time.cpp:97:11: error: ‘localtime_s’ was not declared in this scope; did you mean ‘localtime_r’?
   97 |     (void)localtime_s(&timeNowData, &timeNow);
      |           ^~~~~~~~~~~
      |           localtime_r
make[2]: *** [src/core/CMakeFiles/3DForestCore.dir/build.make:180: src/core/CMakeFiles/3DForestCore.dir/Time.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:657: src/core/CMakeFiles/3DForestCore.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by VaclavBubnik** [comment] 2023-08-04 12:41
Hi sobhonium, Thanks for letting us know about the bug! We've fixed it now, so you shouldn't have any more issues with our software -- hooray!

**Comment by sobhonium** [comment] 2023-08-06 00:59
including **#include &lt;climits&gt;** to **src/core/Utils.hpp** file solves half of issues. But, running >>>make goes well until it runs into errors on threads or something related to that:

/usr/bin/ld: ../../../core/lib3DForestCore.so: undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
make[2]: *** [src/apps/tools/classification/CMakeFiles/3DForestClassification.dir/build.make:101: src/apps/tools/classification/3DForestClassification] Error 1
make[1]: *** [CMakeFiles/Makefile2:510: src/apps/tools/classification/CMakeFiles/3DForestClassification.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by VaclavBubnik** [comment] 2023-08-06 18:08
Hi sobhonium,
Thanks for letting us know about the bug in header files! We've fixed it now. We could not reproduce the issue with pthreads.
We tested the [installation steps](https://vukoz-oel.github.io/3d-forest-documentation/3d-forest-developer-guide.html#build-linux-make) on brand new VM (using VMware) with clean installation of debian-12.1.0-amd64 with LXQt desktop. The app builds and runs fine.

**Comment by sobhonium** [comment] 2023-08-08 05:18
Thanks. I've checked that on another machine with Ubuntu22.04 and it worked with the following edits: 

src/editor/ProgressCounter.hpp :
 + #include &lt;cstddef&gt;

src/editor/QueryFilterSet.hpp :
 size_t --> std::size_t 

src/plugins/explorer/ExplorerWidgetInterface.hpp
+ #include &lt;QIcon&gt;

Don't know why these edits needed or why on different machines different changes needed.

**Comment by VaclavBubnik** [comment] 2023-08-08 18:05
Nice! We are sorry for the bugs. It seems that this issue is now resolved in commit [26bf532 ](https://github.com/VUKOZ-OEL/3d-forest/commit/26bf53221d67d36fbdcbc5ede23890c4ccad11f7) and it could be closed.

**Closed** 2024-10-28 14:22 UTC
